general:
  show_status_bar: true
  history_completions: true
  # this path must have the username changed to work properly.
  history_file: "/home/runner/rbsh_history"
  threaded_completion: true

# The autocomplete is a tree, if you type `sudo` then it'll show the items in `sudo`,
# and anything in `pacman` will be shown when you type `pacman`. It's best understood by example.
autocomplete:
  sudo:
    pacman:
      "-S": None
      "-Syu": None
      "-R": None
  yay:
    "-S": None
    "-R": None
  rbshctl:
    get:
      aliases: None
      completer: None
    version: None
    toggle:
      fuzzy: None
      pymode: None
  help: None
  cd:
    "..": None
    "/": None
  clear: None
  ls:
    "-a": None
  exit: None
  test: None
  goback: None


# The prompt is made from a tree as well
# This is a little more difficult to grasp
prompt:
  order:
    - " :"
  placeholders: None

# As always, the status bar is also a tree.
# The configuration for the status bar is similar to that of the prompt
statusbar:
  order:
    - "RebornShell"
    - " - "
    - "%name"
    - " - "
    - "%pwd"
    - " - IsFuzzy? "
    - "%fuzzy"
  placeholders:
    "%name": "cmd:whoami"
    "%pwd": "utils:pwd"
    "%fuzzy": "utils:isfuzzy"


# Aliases, just a dict, not a tree this time
aliases:
  # alias: command
  ":q": "exit"
  "py": "python3"
  "pymode": "rbshctl toggle pymode"
